config/routes.rb
Rails.application.routes.draw do
  resources :borrowings
  resources :members
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_one :borrowing
  has_one :member, through: :borrowing

  validates :title, presence: true
  validates :isbn, presence: true, uniqueness: true

  def available?
    !borrowing.persisted?
  end
end

app/models/borrowing.rb
class Borrowing < ApplicationRecord
  BORROWING_PERIOD = 14.days.freeze
  BORROWING_LIMIT = 3.freeze

  belongs_to :member
  belongs_to :book

  validate :book_is_available, on: :create
  validate :member_is_under_borrowing_limit, on: :create
  validate :member_has_no_overdue_books, on: :create
  validate :member_has_no_outstanding_fees, on: :create
  validate :member_has_no_duplicate_isbns, on: :create

  before_destroy :validate_borrowing_is_paid

  scope :overdue, -> { where('created_at <= ?', Time.current - BORROWING_PERIOD) }
  scope :unpaid, -> { where(paid: false) }

  delegate :borrowings, :borrowed_isbns, to: :member, prefix: true
  delegate :available?, to: :book, prefix: true

  alias return destroy

  def pay
    update(paid: true)
  end

  private

  def book_is_available
    return if book_available?

    errors.add(:book, "is not available")
  end

  def member_is_under_borrowing_limit
    return if member_borrowings.count < BORROWING_LIMIT

    errors.add(:member, "has reached the borrowing limit")
  end

  def member_has_no_overdue_books
    return if member_borrowings.overdue.none?

    errors.add(:member, "has overdue books")
  end

  def member_has_no_outstanding_fees
    return if member_borrowings.unpaid.none?

    errors.add(:member, "has outstanding fees")
  end

  def member_has_no_duplicate_isbns
    return if member_borrowed_isbns.exclude?(book.isbn)

    errors.add(:member, "has already borrowed this book")
  end

  def validate_borrowing_is_paid
    return if paid?

    errors.add(:base, "you can't return this before you've paid for it")
    throw(:abort)
  end
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :borrowings
  has_many :books, through: :borrowings

  validates :name, presence: true

  def borrowed_isbns
    books.map(&:isbn)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_path, status: :see_other, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :isbn)
    end
end

app/controllers/borrowings_controller.rb
class BorrowingsController < ApplicationController
  before_action :set_borrowing, only: %i[ show edit update destroy ]

  # GET /borrowings or /borrowings.json
  def index
    @borrowings = Borrowing.all
  end

  # GET /borrowings/1 or /borrowings/1.json
  def show
  end

  # GET /borrowings/new
  def new
    @borrowing = Borrowing.new
  end

  # GET /borrowings/1/edit
  def edit
  end

  # POST /borrowings or /borrowings.json
  def create
    @borrowing = Borrowing.new(borrowing_params)

    respond_to do |format|
      if @borrowing.save
        format.html { redirect_to @borrowing, notice: "Borrowing was successfully created." }
        format.json { render :show, status: :created, location: @borrowing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @borrowing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /borrowings/1 or /borrowings/1.json
  def update
    respond_to do |format|
      if @borrowing.update(borrowing_params)
        format.html { redirect_to @borrowing, notice: "Borrowing was successfully updated." }
        format.json { render :show, status: :ok, location: @borrowing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @borrowing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrowings/1 or /borrowings/1.json
  def destroy
    @borrowing.destroy!

    respond_to do |format|
      format.html { redirect_to borrowings_path, status: :see_other, notice: "Borrowing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrowing
      @borrowing = Borrowing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def borrowing_params
      params.require(:borrowing).permit(:member_id, :book_id, :paid)
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy!

    respond_to do |format|
      format.html { redirect_to members_path, status: :see_other, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrowings_helper.rb
module BorrowingsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Isbn:</strong>
    <%= book.isbn %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :isbn, style: "display: block" %>
    <%= form.text_field :isbn %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>

<%= link_to "New book", new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/borrowings/_borrowing.html.erb
<div id="<%= dom_id borrowing %>">
  <p>
    <strong>Member:</strong>
    <%= borrowing.member_id %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= borrowing.book_id %>
  </p>

  <p>
    <strong>Paid:</strong>
    <%= borrowing.paid %>
  </p>

</div>

app/views/borrowings/_form.html.erb
<%= form_with(model: borrowing) do |form| %>
  <% if borrowing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(borrowing.errors.count, "error") %> prohibited this borrowing from being saved:</h2>

      <ul>
        <% borrowing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :member_id, style: "display: block" %>
    <%= form.text_field :member_id %>
  </div>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.text_field :book_id %>
  </div>

  <div>
    <%= form.label :paid, style: "display: block" %>
    <%= form.check_box :paid %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/borrowings/edit.html.erb
<h1>Editing borrowing</h1>

<%= render "form", borrowing: @borrowing %>

<br>

<div>
  <%= link_to "Show this borrowing", @borrowing %> |
  <%= link_to "Back to borrowings", borrowings_path %>
</div>

app/views/borrowings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Borrowings</h1>

<div id="borrowings">
  <% @borrowings.each do |borrowing| %>
    <%= render borrowing %>
    <p>
      <%= link_to "Show this borrowing", borrowing %>
    </p>
  <% end %>
</div>

<%= link_to "New borrowing", new_borrowing_path %>

app/views/borrowings/new.html.erb
<h1>New borrowing</h1>

<%= render "form", borrowing: @borrowing %>

<br>

<div>
  <%= link_to "Back to borrowings", borrowings_path %>
</div>

app/views/borrowings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @borrowing %>

<div>
  <%= link_to "Edit this borrowing", edit_borrowing_path(@borrowing) %> |
  <%= link_to "Back to borrowings", borrowings_path %>

  <%= button_to "Destroy this borrowing", @borrowing, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/members/_member.html.erb
<div id="<%= dom_id member %>">
  <p>
    <strong>Name:</strong>
    <%= member.name %>
  </p>

</div>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Show this member", @member %> |
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Members</h1>

<div id="members">
  <% @members.each do |member| %>
    <%= render member %>
    <p>
      <%= link_to "Show this member", member %>
    </p>
  <% end %>
</div>

<%= link_to "New member", new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @member %>

<div>
  <%= link_to "Edit this member", edit_member_path(@member) %> |
  <%= link_to "Back to members", members_path %>

  <%= button_to "Destroy this member", @member, method: :delete %>
</div>